
  CREATE TABLE "CAREERS"."ADMIN"
   (	"ID" VARCHAR2(36 BYTE),
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"USER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
	"SALT" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"IS_TRAINING_ADMIN" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"IS_MEDIA_ADMIN" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"IS_CAREER_ADMIN" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"IS_PROCUREMENT_ADMIN" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"IS_SUPER_ADMIN" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"IS_BLOCKED" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"LAST_LOGIN" DATE,
	"RESET_PASS" NUMBER DEFAULT 0
   ) ;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_TRAINING_CK" CHECK (Is_Training_Admin in (0,1)) ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_MEDIA_CK" CHECK (Is_Media_Admin in (0,1)) ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_CAREER_CK" CHECK (Is_Career_Admin in (0,1)) ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_PROCUREMENT_CK" CHECK (Is_Procurement_Admin in (0,1)) ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_SUPER_CK" CHECK (Is_Super_Admin in (0,1)) ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_BLOCK_CK" CHECK (Is_Blocked in (0,1)) ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_USERNAME_UK" UNIQUE ("USER_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "CAREERS"."ADMIN" ADD CONSTRAINT "ADMIN_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX  ENABLE;
