
  CREATE TABLE "CAREERS"."ATTACHMENTS_DETAILS"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"FILE_BLOB" BLOB NOT NULL ENABLE,
	"MIME_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"EXTENSION" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"MD5" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"FILE_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "CAREERS"."ATTACHMENTS_DETAILS" ADD CONSTRAINT "ATTACHMENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "CAREERS"."ATTACHMENTS_DETAILS" ADD CONSTRAINT "ATTACHMENT_ACCOUNT_FK" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "CAREERS"."ACCOUNT" ("ID") ENABLE;
