
  CREATE TABLE "CAREERS"."JOB_VACANCY_APPLICATION_DUP_BKP"
   (	"ID" NUMBER NOT NULL ENABLE,
	"VACANCY_ID" NUMBER NOT NULL ENABLE,
	"APPLICATION_ID" NUMBER NOT NULL ENABLE,
	"IS_ARCHIVED" NUMBER NOT NULL ENABLE,
	"DATE_TIME" DATE
   ) ;
