
  CREATE TABLE "CAREERS"."JOB_APP_EXP_ORPHAN_BKP"
   (	"ID" NUMBER NOT NULL ENABLE,
	"POSITION_NAME" CLOB NOT NULL ENABLE,
	"COMPANY" CLOB NOT NULL ENABLE,
	"FROMDATE" DATE NOT NULL ENABLE,
	"OTHER_DETAILS" CLOB,
	"JOB_APPLICATION_ID" NUMBER,
	"COUNTRY_ID" NUMBER,
	"PERSONAL_ID" NUMBER,
	"TODATE" DATE
   ) ;
