
  CREATE TABLE "CAREERS"."JOB_APPLICATION_ORPHAN_BKP"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ACCOUNT_ID" NUMBER NOT NULL ENABLE,
	"CREATION_DATE" DATE,
	"LAST_UPDATE_DATE" DATE,
	"IS_ARCHIVED" NUMBER(1,0) NOT NULL ENABLE,
	"ARCHIVING_REASON" CLOB,
	"ARCHIVED_DATE" DATE,
	"RESUME_FILE_ID" NUMBER
   ) ;
